import type { SpaceObject } from './spaceTypes'

export const spaceObjects: SpaceObject[] = [
  {
    id: 'horse-motion',
    kind: 'image',
    title: 'The Horse in Motion',
    subtitle: 'Eadweard Muybridge · 1878',
    source: 'Wikimedia Commons',
    x: -58,
    y: 20,
    z: 6,
    width: 410,
    height: 520,
    tags: ['motion', 'photography', 'history', 'interaction'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Muybridge_race_horse_animated.gif',
    accent: '#d8d1c2',
    meta: 'A sequence becomes an interface once time is made spatial.',
    priority: 3,
  },
  {
    id: 'information-landscapes',
    kind: 'article',
    title: 'Information Landscapes',
    subtitle: 'Muriel Cooper · MIT · 1994',
    source: 'Visible Language Workshop',
    x: -27,
    y: 28,
    z: -18,
    width: 610,
    height: 350,
    tags: ['typography', 'spatial', 'design', 'interaction'],
    accent: '#efede7',
    meta: 'Typography treated as navigable space rather than a page.',
    priority: 3,
  },
  {
    id: 'magic-lens',
    kind: 'paper',
    title: 'Toolglass + Magic Lenses',
    subtitle: 'Bier et al. · Xerox PARC · 1993',
    source: 'Research paper',
    x: 12,
    y: 22,
    z: -45,
    width: 470,
    height: 310,
    tags: ['lens', 'semantic', 'interface', 'research'],
    accent: '#d7d4ca',
    meta: 'A second interpretation of the same scene, revealed locally.',
    priority: 3,
  },
  {
    id: 'synchromy',
    kind: 'video',
    title: 'Synchromy',
    subtitle: 'Norman McLaren · 1971',
    source: 'Film',
    x: 46,
    y: 20,
    z: 1,
    width: 520,
    height: 320,
    tags: ['motion', 'sound', 'visual', 'signal'],
    image: 'https://i.ytimg.com/vi/jiJR1ET715M/hqdefault.jpg',
    accent: '#d42f25',
    meta: 'One signal becomes image and sound.',
    priority: 3,
  },
  {
    id: 'rotoreliefs',
    kind: 'image',
    title: 'Rotoreliefs',
    subtitle: 'Marcel Duchamp · 1935',
    source: 'Optical study',
    x: 78,
    y: 12,
    z: -72,
    width: 350,
    height: 350,
    tags: ['optical', 'motion', 'art', 'perception'],
    accent: '#e9e5d9',
    meta: 'Flat graphics become depth through rotation and perception.',
  },
  {
    id: 'data-mountain',
    kind: 'paper',
    title: 'Data Mountain',
    subtitle: 'Microsoft Research · 1998',
    source: 'Research paper',
    x: -66,
    y: -17,
    z: -35,
    width: 520,
    height: 330,
    tags: ['bookmarks', 'spatial', 'memory', 'research'],
    accent: '#cbc7bc',
    meta: 'Spatial memory applied directly to saved web documents.',
    priority: 3,
  },
  {
    id: 'bookmark-cluster',
    kind: 'cluster',
    title: 'Spatial interfaces',
    subtitle: '5 connected references',
    source: 'Collection',
    x: -32,
    y: -7,
    z: 14,
    width: 420,
    height: 300,
    tags: ['spatial', 'interface', 'bookmarks', 'research'],
    accent: '#171715',
    meta: 'A pile is an object until you ask it to become a path.',
    priority: 3,
  },
  {
    id: 'react-native-edge-fade',
    kind: 'repo',
    title: 'react-native-edge-fade',
    subtitle: 'Native UI primitive',
    source: 'GitHub',
    x: 1,
    y: -5,
    z: -14,
    width: 560,
    height: 330,
    tags: ['github', 'native', 'motion', 'blur'],
    accent: '#111111',
    meta: 'AGSL · Metal · progressive blur',
    priority: 3,
  },
  {
    id: 'minimal-house',
    kind: 'audio',
    title: 'Ion Ludwig',
    subtitle: 'Minimal / electronic',
    source: 'Listening reference',
    x: 40,
    y: -7,
    z: -58,
    width: 390,
    height: 390,
    tags: ['music', 'minimal', 'audio', 'electronic'],
    accent: '#a98a69',
    meta: 'A saved sound should still feel like sound.',
    priority: 2,
  },
  {
    id: 'codrops-infinite',
    kind: 'article',
    title: 'Infinite Canvas',
    subtitle: 'Edoardo Lunardi · Codrops · 2026',
    source: 'Codrops',
    x: -57,
    y: -39,
    z: -86,
    width: 680,
    height: 410,
    tags: ['canvas', 'spatial', 'web', 'interaction'],
    accent: '#201f1d',
    meta: 'Chunked rendering, inertial camera and a world that continues past the viewport.',
    priority: 3,
  },
  {
    id: 'grid-zoom',
    kind: 'article',
    title: 'Grid Zoom Layout',
    subtitle: 'Manoela Ilic · Codrops · 2021',
    source: 'Codrops',
    x: -14,
    y: -37,
    z: -28,
    width: 590,
    height: 360,
    tags: ['focus', 'continuity', 'zoom', 'interaction'],
    accent: '#e7e3d8',
    meta: 'The selected thing grows into the next state instead of navigating away.',
    priority: 3,
  },
  {
    id: 'oramics',
    kind: 'image',
    title: 'Oramics Machine',
    subtitle: 'Daphne Oram · 1962',
    source: 'Science Museum',
    x: 25,
    y: -40,
    z: -104,
    width: 420,
    height: 530,
    tags: ['sound', 'drawing', 'signal', 'history'],
    image: 'https://coimages.sciencemuseumgroup.org.uk/22/850/medium_2010_0068_0002__0001_.jpg',
    accent: '#d8cfbd',
    meta: 'Drawing becomes behavior.',
    priority: 2,
  },
  {
    id: 'shadowfax',
    kind: 'video',
    title: 'Shadowfax',
    subtitle: 'Kris Puckett · motion study',
    source: 'Interaction study',
    x: 59,
    y: -38,
    z: -42,
    width: 560,
    height: 350,
    tags: ['motion', 'apple', 'history', 'interaction'],
    accent: '#181818',
    meta: 'Historical motion recast as a contemporary interface behavior.',
    priority: 3,
  },
  {
    id: 'thumbnail-flow',
    kind: 'article',
    title: 'Thumbnail Flow',
    subtitle: 'Iqbal Muthahhary · Codrops · 2026',
    source: 'Codrops',
    x: 88,
    y: -28,
    z: -115,
    width: 430,
    height: 300,
    tags: ['motion', 'path', 'stack', 'interaction'],
    accent: '#d8d3c5',
    meta: 'A compact stack unfolds through curved trajectories and tiny stagger.',
    priority: 2,
  },
]
