import type { SpaceObject } from './spaceTypes'

export const HOME_CAMERA = {
  x: 80,
  y: 90,
} as const

export const spaceObjects: SpaceObject[] = [
  {
    id: 'horse-motion',
    kind: 'image',
    title: 'The Horse in Motion',
    subtitle: 'Eadweard Muybridge · 1878',
    source: 'Wikimedia Commons',
    x: -1080,
    y: -330,
    width: 410,
    height: 520,
    tags: ['motion', 'photography', 'history', 'interaction'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Muybridge_race_horse_animated.gif',
    accent: '#d8d1c2',
    meta: 'A sequence becomes an interface once time is made spatial.',
    priority: 3,
  },
  {
    id: 'information-landscapes',
    kind: 'article',
    title: 'Information Landscapes',
    subtitle: 'Muriel Cooper · MIT · 1994',
    source: 'Visible Language Workshop',
    x: -520,
    y: -455,
    width: 610,
    height: 350,
    tags: ['typography', 'spatial', 'design', 'interaction'],
    accent: '#efede7',
    meta: 'Typography treated as navigable space rather than a page.',
    priority: 3,
  },
  {
    id: 'magic-lens',
    kind: 'paper',
    title: 'Toolglass + Magic Lenses',
    subtitle: 'Bier et al. · Xerox PARC · 1993',
    source: 'Research paper',
    x: 220,
    y: -410,
    width: 470,
    height: 310,
    tags: ['lens', 'semantic', 'interface', 'research'],
    accent: '#d7d4ca',
    meta: 'A second interpretation of the same scene, revealed locally.',
    priority: 3,
  },
  {
    id: 'synchromy',
    kind: 'video',
    title: 'Synchromy',
    subtitle: 'Norman McLaren · 1971',
    source: 'Film',
    x: 820,
    y: -365,
    width: 520,
    height: 320,
    tags: ['motion', 'sound', 'visual', 'signal'],
    image: 'https://i.ytimg.com/vi/jiJR1ET715M/hqdefault.jpg',
    accent: '#d42f25',
    meta: 'One signal becomes image and sound.',
    priority: 3,
  },
  {
    id: 'rotoreliefs',
    kind: 'image',
    title: 'Rotoreliefs',
    subtitle: 'Marcel Duchamp · 1935',
    source: 'Optical study',
    x: 1430,
    y: -230,
    width: 350,
    height: 350,
    tags: ['optical', 'motion', 'art', 'perception'],
    accent: '#e9e5d9',
    meta: 'Flat graphics become depth through rotation and perception.',
  },
  {
    id: 'data-mountain',
    kind: 'paper',
    title: 'Data Mountain',
    subtitle: 'Microsoft Research · 1998',
    source: 'Research paper',
    x: -1240,
    y: 300,
    width: 520,
    height: 330,
    tags: ['bookmarks', 'spatial', 'memory', 'research'],
    accent: '#cbc7bc',
    meta: 'Spatial memory applied directly to saved web documents.',
    priority: 3,
  },
  {
    id: 'bookmark-cluster',
    kind: 'cluster',
    title: 'Spatial interfaces',
    subtitle: '5 connected references',
    source: 'Collection',
    x: -590,
    y: 120,
    width: 420,
    height: 300,
    tags: ['spatial', 'interface', 'bookmarks', 'research'],
    accent: '#171715',
    meta: 'A pile is an object until you ask it to become a path.',
    priority: 3,
  },
  {
    id: 'react-native-edge-fade',
    kind: 'repo',
    title: 'react-native-edge-fade',
    subtitle: 'Native UI primitive',
    source: 'GitHub',
    x: 30,
    y: 95,
    width: 560,
    height: 330,
    tags: ['github', 'native', 'motion', 'blur'],
    image: 'https://opengraph.githubassets.com/1/AmatoGiulio/react-native-edge-fade',
    accent: '#111111',
    meta: 'AGSL · Metal · progressive blur',
    priority: 3,
  },
  {
    id: 'minimal-house',
    kind: 'audio',
    title: 'Ion Ludwig',
    subtitle: 'Minimal / electronic',
    source: 'Listening reference',
    x: 720,
    y: 120,
    width: 390,
    height: 390,
    tags: ['music', 'minimal', 'audio', 'electronic'],
    accent: '#a98a69',
    meta: 'A saved sound should still feel like sound.',
    priority: 2,
  },
  {
    id: 'codrops-infinite',
    kind: 'article',
    title: 'Infinite Canvas',
    subtitle: 'Edoardo Lunardi · Codrops · 2026',
    source: 'Codrops',
    x: -1090,
    y: 730,
    width: 680,
    height: 410,
    tags: ['canvas', 'spatial', 'web', 'interaction'],
    image: 'https://codrops-1f606.kxcdn.com/codrops/wp-content/uploads/2025/12/edoardo-lunardi-infinite-canvas-3.jpg',
    accent: '#201f1d',
    meta: 'Chunked rendering, inertial camera and a world that continues past the viewport.',
    priority: 3,
  },
  {
    id: 'grid-zoom',
    kind: 'article',
    title: 'Grid Zoom Layout',
    subtitle: 'Manoela Ilic · Codrops · 2021',
    source: 'Codrops',
    x: -280,
    y: 660,
    width: 590,
    height: 360,
    tags: ['focus', 'continuity', 'zoom', 'interaction'],
    image: 'https://codrops-1f606.kxcdn.com/codrops/wp-content/uploads/2021/12/GridZoom_02-800x500.jpg',
    accent: '#e7e3d8',
    meta: 'The selected thing grows into the next state instead of navigating away.',
    priority: 3,
  },
  {
    id: 'oramics',
    kind: 'image',
    title: 'Oramics Machine',
    subtitle: 'Daphne Oram · 1962',
    source: 'Science Museum',
    x: 470,
    y: 720,
    width: 420,
    height: 530,
    tags: ['sound', 'drawing', 'signal', 'history'],
    image: 'https://coimages.sciencemuseumgroup.org.uk/22/850/medium_2010_0068_0002__0001_.jpg',
    accent: '#d8cfbd',
    meta: 'Drawing becomes behavior.',
    priority: 2,
  },
  {
    id: 'shadowfax',
    kind: 'video',
    title: 'Shadowfax',
    subtitle: 'Kris Puckett · motion study',
    source: 'Interaction study',
    x: 1060,
    y: 690,
    width: 560,
    height: 350,
    tags: ['motion', 'apple', 'history', 'interaction'],
    accent: '#181818',
    meta: 'Historical motion recast as a contemporary interface behavior.',
    priority: 3,
  },
  {
    id: 'thumbnail-flow',
    kind: 'article',
    title: 'Thumbnail Flow',
    subtitle: 'Iqbal Muthahhary · Codrops · 2026',
    source: 'Codrops',
    x: 1600,
    y: 500,
    width: 430,
    height: 300,
    tags: ['motion', 'path', 'stack', 'interaction'],
    accent: '#d8d3c5',
    meta: 'A compact stack unfolds through curved trajectories and tiny stagger.',
    priority: 2,
  },
]
