import type { SpaceObject } from './spaceTypes'

export const spaceObjects: SpaceObject[] = [
  {
    id: 'horse-motion',
    kind: 'paper',
    title: 'The Horse in Motion',
    subtitle: 'Eadweard Muybridge · 1878',
    x: -610,
    y: -360,
    width: 290,
    height: 370,
    tags: ['motion', 'photography', 'history', 'interaction'],
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Muybridge_race_horse_animated.gif',
    accent: '#d8d1c2',
  },
  {
    id: 'information-landscapes',
    kind: 'article',
    title: 'Information Landscapes',
    subtitle: 'Muriel Cooper · MIT',
    x: -170,
    y: -500,
    width: 350,
    height: 230,
    tags: ['typography', 'spatial', 'design', 'interaction'],
    accent: '#f2f2ef',
  },
  {
    id: 'magic-lens',
    kind: 'paper',
    title: 'Toolglass + Magic Lenses',
    subtitle: 'Xerox PARC · 1993',
    x: 410,
    y: -410,
    width: 300,
    height: 210,
    tags: ['lens', 'semantic', 'interface', 'research'],
    accent: '#dad9d3',
    meta: 'See-through interfaces as tools',
  },
  {
    id: 'synchromy',
    kind: 'video',
    title: 'Synchromy',
    subtitle: 'Norman McLaren · 1971',
    x: 850,
    y: -170,
    width: 360,
    height: 230,
    tags: ['motion', 'sound', 'visual', 'signal'],
    accent: '#d42f25',
  },
  {
    id: 'data-mountain',
    kind: 'paper',
    title: 'Data Mountain',
    subtitle: 'Microsoft Research · 1998',
    x: -770,
    y: 130,
    width: 340,
    height: 225,
    tags: ['bookmarks', 'spatial', 'memory', 'research'],
    accent: '#dbd8cf',
    meta: 'Spatial memory for document management',
  },
  {
    id: 'bookmark-cluster',
    kind: 'cluster',
    title: 'Spatial interfaces',
    subtitle: '8 references',
    x: -190,
    y: 90,
    width: 320,
    height: 240,
    tags: ['spatial', 'interface', 'bookmarks', 'research'],
    accent: '#111111',
  },
  {
    id: 'react-native-edge-fade',
    kind: 'repo',
    title: 'react-native-edge-fade',
    subtitle: 'GitHub · native UI primitive',
    x: 330,
    y: 80,
    width: 355,
    height: 215,
    tags: ['github', 'native', 'motion', 'blur'],
    accent: '#141414',
    meta: 'AGSL · Metal · progressive blur',
  },
  {
    id: 'minimal-house',
    kind: 'audio',
    title: 'Ion Ludwig — Selene',
    subtitle: 'audio reference',
    x: 780,
    y: 290,
    width: 280,
    height: 280,
    tags: ['music', 'minimal', 'audio', 'electronic'],
    accent: '#b99f7f',
  },
  {
    id: 'rotoreliefs',
    kind: 'image',
    title: 'Rotoreliefs',
    subtitle: 'Marcel Duchamp · 1935',
    x: -540,
    y: 560,
    width: 260,
    height: 260,
    tags: ['optical', 'motion', 'art', 'perception'],
    accent: '#f1efe9',
  },
  {
    id: 'codrops-canvas',
    kind: 'article',
    title: 'Infinite Canvas',
    subtitle: 'Codrops · Edoardo Lunardi',
    x: -80,
    y: 520,
    width: 390,
    height: 250,
    tags: ['canvas', 'spatial', 'web', 'interaction'],
    accent: '#efeee8',
    meta: 'Pan-anywhere image space',
  },
  {
    id: 'oramics',
    kind: 'image',
    title: 'Oramics Machine',
    subtitle: 'Daphne Oram · 1962',
    x: 480,
    y: 570,
    width: 300,
    height: 360,
    tags: ['sound', 'drawing', 'signal', 'history'],
    accent: '#ded7c9',
  },
  {
    id: 'shadowfax',
    kind: 'video',
    title: 'Shadowfax',
    subtitle: 'Kris Puckett · motion study',
    x: 960,
    y: 650,
    width: 330,
    height: 210,
    tags: ['motion', 'apple', 'history', 'interaction'],
    accent: '#181818',
  },
]
